//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaHomesDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelAmenity
    {
        public int AmenityId { get; set; }
        public int HotelId { get; set; }
    }
}
